### ISSUE TITLE
Issue with Apple CarPlay

### ISSUE THREAD

**Issue by rijink7** [EinfachHans/cordova-plugin-advanced-background-mode#1] opened 2020-03-03 05:00 UTC
Tested Background plugin with CarPlay.It is blocking streaming apps from playing via Apple CarPlay, which I think is a symptom of the larger background problem. 
1.) In my car, when app is opened and I try to play music on my phone through another streaming service, the music from the streaming service bypasses the car system and directly plays through the iPhone speakers.
When I force quit app, the music starts playing through the car speaker system via CarPlay

**Comment by EinfachHans** [comment] 2020-03-03 07:11
Sadly i'm not as much into this deep in native ios development. I did some research but don't found something. Also i can't reproduce/ test this.

So if you can fix this and create a PR i will love to merge it!

**Comment by biancasalvatore** [comment] 2020-07-20 14:50
on a hawaii p30 lite it does not work on the contrary the app is always closed as soon as it focuses
on another cell samsung s5 works well

**Closed as not planned** 2024-01-29 12:10 UTC
Labels: bug, help wanted
